language: python
python:
  - "3.5"
before_install:
    #- sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
    #- sudo apt-get install python3-sip python3-sip-dev python3-pyqt4 cmake
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz 
  - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz -o /downloads/pyqt4.tar.gz
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
install:
  # Qt4
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui
  - make
  - sudo make install
  - popd
  # Builds Complete
  - popd
  - pip install -r requirements.txt
  - cp -r /usr/lib/python3/dist-packages/* /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/
script: nosetests --exe --with-coverage --cover-erase --cover-html --cover-package=gui_export.py,service.py,handler.py
